spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/reed?serverTimezone=Asia/Seoul
    url: jdbc:mysql://52.79.171.108:3306/reed?serverTimezone=Asia/Seoul
    username: reed
    password: qwer1234!@#$


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'reedu06@gmail.com'
    password: 'evtflyyznjwcbxhm'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            timeout: 5000

# JWT
# https://jwt.io/introduction
application:
  security:
    jwt:
      secretKey: 25432A462D4A614E645267556A586E3272357538782F413F4428472B4B625065
      expiration: 3600000 #1 hour
      refreshExpiration: 1296000000 #15 day

# swagger
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
#    operations-sorter: alpha

neis:
  api:
    key: a0e266dd67df41eaa34ead1e81f31846
    baseUrl: https://open.neis.go.kr/hub

firebase:
  sdk:
    path: reed-b4725-firebase-adminsdk-5eqzt-0f5206b86a.json
